CREATE TABLE CUSTOMER(
USERID	VARCHAR2(10) NOT NULL,	 --회원코드
USERPW	VARCHAR2(20) NOT NULL,	 --비밀번호
USERNAME	VARCHAR2(15) NOT NULL,	 --이름
USERGRADE	CHAR(2) NOT NULL,	 --등급
USERNICK	VARCHAR2(20) NOT NULL,	 --닉네임
USERPHONE	NUMBER(11) NOT NULL,	 --연락처(전화번호)
USEREMAIL	VARCHAR2(30) NOT NULL,	 --이메일
USERGOOD	NUMBER(10) DEFAULT '0',	 --유저추천수
USERPHOTO	VARCHAR2(50),	 --회원사진
USERREGDATE DATE	 --가입일
);

ALTER TABLE CUSTOMER ADD(
CONSTRAINT PK_CUSTOMER_USERID PRIMARY KEY(USERID));